### ISSUE TITLE
Imported GeoJSON Does Not Generate Blocks in Schematic

### ISSUE THREAD

**Issue by kyanvde** [Codestian/TerraSketch#1]
**Description:** I encountered an issue while using the TerraSketch program. I imported a GeoJSON file and attempted to create a schematic from it. However, when I paste the schematic in-game, no blocks appear.

**Steps to Reproduce:**

Import an external GeoJSON file into TerraSketch.
Create a schematic from the imported data.
Paste the schematic in-game.
Observe that no blocks appear, despite the schematic being pasted correctly.

**Expected Behavior:** The schematic should generate blocks in-game according to the imported GeoJSON data.

**Actual Behavior:** The schematic pastes correctly, but no blocks appear.

**Additional Information:**
It seems the issue is related to missing GeoJSON attributes such as elevation and block type, which are necessary for the schematic to generate blocks properly. These attributes are present when creating a polygon from inside the program but not when importing it from an external source.

**Comment by Codestian** [comment]
Issue has been fixed
